---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-x86
  namespace: default
  labels:
    app: nginx-x86
    architecture: x86
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-x86
  template:
    metadata:
      labels:
        app: nginx-x86
        architecture: x86
    spec:
      # Node selection for x86 architecture
      nodeSelector:
        kubernetes.io/arch: amd64
        karpenter.sh/nodepool: x86-pool
      # Tolerate the x86-pool taint
      tolerations:
      - key: x86-pool
        operator: Equal
        value: "true"
        effect: NoSchedule
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
          name: http
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-x86
  namespace: default
spec:
  selector:
    app: nginx-x86
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  type: LoadBalancer